### PR TITLE
Change the PR template back

### PR DESCRIPTION
**Pull request by TheGiraffe3**
Well, since this PR is about reverting the template change, I think I'll skip filling out the template...

Except for that this "feature" was requested in https://github.com/endless-sky/Endless-Sky-Delta/pull/54#issuecomment-2383480479.

### CODE REVIEW

**Comment by TheGiraffe3** [comment]
Also, do we want to add to the issue template an option to report bugs with the upstream version?

**Comment by Zitchas** [comment]
Just a thought/question: Would it be possible to have an issues-style thing for PRs where one clicks a button to get the appropriate template?

**Comment by TheGiraffe3** [comment]
> Just a thought/question: Would it be possible to have an issues-style thing for PRs where one clicks a button to get the appropriate template?

I don't think that's possible, unfortunately. Nobody I've seen (including some GitHub repositories) does that. I'll check, though.

**Comment by TheGiraffe3** [comment]
Well, the [Docs article](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/using-query-parameters-to-create-a-pull-request) about pull request templates is somewhat unclear, but it looks like it's not possible.

**Comment by TheGiraffe3** [comment]
https://github.com/github/docs/issues/34811
I'm still a trifle unclear about how this is supposed to work. @Zitchas do you have any clarifications?
It seems that having multiple is _possible_, but I'm finding it difficult to find out how.
https://github.com/TheGiraffe3/pull-request-template-test: I've been working on it, but no luck yet.

**Comment by warp-core** [comment]
The presence of multiple files in the `PULL_REQUEST_TEMPLATE` subdirectory can be used with the `template` query parameter when using a URL to open a pull request.
For example, if there were a file in that directory named `whatever.md`, and I wanted to reach the page for opening a pull request with the pull request body pre-filled with that template, instead of the default template, or nothing, in the case of no default template, I could use the URL:
`https://github.com/endless-sky/Endless-Sky-Delta/compare/endless-sky:Endless-Sky-Delta:experimental...warp-core:endless-sky:my_branch?quick_pull=1&template=whatever.md`

See the "template" row in the table on this page: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/using-query-parameters-to-create-a-pull-request

**Comment by Zitchas** [comment]
That sounds promising.

**Comment by TheGiraffe3** [comment]
But it does mean the person making the PR has to know what URL to use, which was my problem.

**Comment by Zitchas** [comment]
If we can have a variety of set up templates, and the problem is people not having links to them, could we just have a discussion or an issue that lists off a while bunch of different template links? 

Ex. New content with images (ships, outfits, planets, etc), content with no images, mechanics, bug fixes, etc.

**Comment by TheGiraffe3** [comment]
Or add that to the CONTRIBUTING document.

**Pull request closed without merging**
