### PR TITLE
Feat(update): 2024-12-22 update requiring careful handling due to removal of erase breaking the compilation

### PR DESCRIPTION
**Pull request by Zitchas**
As discovered in the initial attempt to update Delta in PR https://github.com/endless-sky/Endless-Sky-Delta/pull/185 , it appears that the removal of the erase functionality in https://github.com/endless-sky/endless-sky/pull/10865 has resulted in the code for controlling fleet numbers originally proposed in https://github.com/endless-sky/endless-sky/pull/8082 and merged into Delta in https://github.com/endless-sky/Endless-Sky-Delta/pull/24 has been broken, as evidenced by the original update PR's failure to compile traced to elements calling for erases.

This update PR pulls from a standalone branch instead of directly from upstream in order to allow better handling of the update, with the strong possibility that it may simply be reverting upstream's removal of the erase functionality.

(Including the "bug" label here because the upstream update specifically causes a problem)

### CODE REVIEW

**Comment by Zitchas** [comment]
The error from the CD/Linux compile:
```
   Error: /home/runner/work/Endless-Sky-Delta/Endless-Sky-Delta/source/PlayerInfo.cpp:3998:28: error: ‘class ConditionsStore::DerivedProvider’ has no member named ‘SetEraseFunction’; did you mean ‘SetSetFunction’?
   3998 |         fleetCountProvider.SetEraseFunction([this](const string &name) -> bool
        |                            ^~~~~~~~~~~~~~~~
        |                            SetSetFunction
```

Which makes sense, since SetEraseFunction is the first thing removed:

```
void ConditionsStore::DerivedProvider::SetEraseFunction(function<bool(const string &)> newEraseFun)
{
	eraseFunction = std::move(newEraseFun);
}
```

**Comment by Zitchas** [comment]
@UnorderedSigh I would appreciate your input here, as you wrote the fleet count control code that I think this impacts. Is it possible to adjust that to not need this? Would it be better to simply revert the refactor to retain the functionality? From my perspective, if working around this refactor will mean basiscally coding a replacement for it that just serves the one bit of code, then it would make more sense to just revert this removal of the erase functionality entirely instead.

**Comment by petervdmeer** [comment]
> @UnorderedSigh I would appreciate your input here, as you wrote the fleet count control code that I think this impacts.

The erase function is simply not needed. It was never needed, I originally included it by mistake when I first wrote the auto-conditions and the templates for them. (And I corrected that mistake in a recent PR.)

> Is it possible to adjust that to not need this?

Yes, the adjustment should involve deleting 5 lines of code that are no longer needed.

> Would it be better to simply revert the refactor to retain the functionality?

I think the most important thing to recognize here is that this is technically not a bug, but a merge-conflict between #8082 and #10865. As with any merge-conflict; if #8082 got merged first, then I would have handled the conflict in #10865, and if #10865 got merged first, then #8082 needs an update to handle the merge conflict.

Nobody is really at fault here, there are just 2 PRs that were open in parallel that had conflicting changes.

**Comment by Zitchas** [comment]
Here in Delta, I use the "Bug" tag a bit more liberally. If something's broken or breaking or otherwise needs some work to resolve, it's a bug. Likewise if something gets merged upstream that causes problems here, then it's a bug, as something merged upstream is something that is, effectively already merged here, it just hasn't actually arrived until I update. 

I'm not throwing blame, it's a fact of life that conflicts are going to happen. It's just a bit more visible than usual because it's removing functionality that, at least at the PR level, looked like it was being used, and I wasn't (and still aren't) sure exactly how to resolve it to ensure zero impact on the desired functionality that contains those references. That being said, I just about to delve into it now. I appreciate the various pointers and comments that have provided some additional info to assist with that.

**Comment by Zitchas** [comment]
Case in point: It seems a little unbelievable that something as simple as "erasing" something would explicitly be built into the game and supported, and then someone builds something that explicitly includes that in their code, just to have it do absolutely nothing to the point of being able to just snip it out. Especially when dealing with specifying exact numbers of ships to be present, setting something to zero isn't actually the same thing as erasing it. 

I can definitely delete things until it compiles and generates no errors; sure; but that's not the same thing as verifying that it has *all* the functionality originally included in the PR. In this particular case, I do mean *all* the functionality of the original PR, not just "All the functionality that upstream cares to support." These two *may* be the same thing, but aren't forcibly so.

This is why I'd like Unordered's insight, since they wrote the original PR in question. More eyes make for better code, and all that. 

That, and a bit more information than just "delete five lines of code" would be appreciated. (beyond just deleting the segment the below segment in PlayerInfo.cpp: (shown commented out, because that's what I'm doing at the moment)

```
	// fleetCountProvider.SetEraseFunction([this](const string &name) -> bool
	// {
	// 	string fleetName = name.substr(strlen("fleet count by name: "));
	// 	fleetCounters.erase(fleetName);
	// 	return true;
	// });
```

**Comment by Zitchas** [comment]
OK, I had to fight with the test file. Not sure why the mission wasn't loading from the test file, but in any case, ended up using the below code pasted into a regular data file in order to get the test mission to run.

<details>

<summary>My version of UnorderedSigh's test mission</summary>

```




mission "Mega Special Testing Job"
	name "AAA This is the Testing Job"
	landing
	description "Deliver <cargo> to <destination>. Payment is <payment>."
	cargo random 5 2 .1
	payment 20000000
	source
		government "Republic" "Free Worlds" "Syndicate" "Neutral" "Independent"
	destination
		distance 2 8
		government "Republic" "Free Worlds" "Syndicate" "Neutral" "Independent"
	on visit
		dialog phrase "generic cargo on visit"
	on complete
		payment
		dialog phrase "generic cargo delivery payment"
	on offer
		conversation
			`Adding Pug vs. Drak fight at Cardax.`
			`Adding Remnant vs. Korath fight at Moktar where the Korath run out of ships because they're all disabled.`
			`Adding Remnant vs. Korath fight at Durax where the Korath arrival limit ignores disabled fleets.`
			`Adding a guardian Archon in Korath Exile space.`
				accept
	on accept
		event "korath archons"
		event "pug vs drak at cardax"
		event "remnant vs korath at moktar"
		event "remnant vs korath at durax"


fleet "Pug Arfecta"
	government Pug
	names pug
	personality heroic staying
	variant
		"Pug Arfecta" 6

fleet "Archon (Cloaked)"
	government Drak
	personality heroic staying
	variant
		"Archon (Cloaked)"

fleet "Archon"
	government Drak
	personality heroic staying
	variant
		"Archon"

fleet "Heron"
	government Remnant
	personality heroic staying
	variant
		"Heron" 3

event "pug vs drak at cardax"
	system Cardax
		fleet "Pug Arfecta"
			period 100
			initial count 10
			limit 12
			ignore enemy strength
		fleet "Archon (Cloaked)"
			period 500
			initial count 1
			limit 1

event "remnant vs korath at moktar"
	system Moktar
		fleet "Korath Raid"
			period 500
			initial count 3
			limit 7
			category korath
			ignore enemy strength
		fleet "Korath Large Raid"
			period 500
			initial count 3
			limit 3
			category korath
			ignore enemy strength
		fleet "Heron"
			period 1200
			limit 1
			skip system entry
			category remnant
			ignore enemy strength
		fleet "Small Remnant"
			period 500
			initial count 1
			limit 3
			category remnant
			ignore enemy strength
		fleet "Large Remnant"
			period 500
			initial count 11
			limit 2
			category remnant
			ignore enemy strength

event "remnant vs korath at durax"
	system Durax
		fleet "Korath Raid"
			period 500
			initial count 3
			non-disabled limit 7
			category "korath ignore disabled"
			ignore enemy strength
		fleet "Korath Large Raid"
			period 500
			initial count 3
			non-disabled limit 3
			category "korath ignore disabled"
			ignore enemy strength
		fleet "Heron"
			period 1200
			limit 1
			skip system entry
			category "remnant ignore disabled"
			ignore enemy strength
		fleet "Small Remnant"
			period 500
			initial count 1
			non-disabled limit 3
			category "remnant ignore disabled"
			ignore enemy strength
		fleet "Large Remnant"
			period 500
			initial count 11
			non-disabled limit 2
			category "remnant ignore disabled"
			ignore enemy strength

event "korath archons"
	system "Kor Ak'Mari"
		fleet "Archon" 500
			initial count 1
			limit 1
			category "korath guard"
	system "Kor En'lakfar"
		fleet "Archon" 500
			initial count 1
			limit 1
			category "korath guard"
	system "Kor Fel'tar"
		fleet "Archon" 500
			initial count 1
			limit 1
			category "korath guard"
	system "Kor Men"
		fleet "Archon" 500
			initial count 1
			limit 1
			category "korath guard"
	system "Kor Nor'peli"
		fleet "Archon" 500
			initial count 1
			limit 1
			category "korath guard"
	system "Kor Tar'bei"
		fleet "Archon" 500
			initial count 1
			limit 1
			category "korath guard"
	system "Kor Zena'i"
		fleet "Archon" 500
			initial count 1
			limit 1
			category "korath guard"
```

edit: Yes, I did paste their TestEvent mission into the most basic cargo delivery job I could find, with some tweaks. It works, it's not pretty. Not sure why the original mission in the limittest file wasn't working.

</details>

**Comment by warp-core** [comment]
> That, and a bit more information than just "delete five lines of code" would be appreciated.

`ConditionsStore` is a class that handles the storage of conditions. That is, it stores keys (the string condition names) and their corresponding values. When a condition set is evaluated and the values of conditions are needed, they are retrieved from the relevant `ConditionsStore` object. When conditions are being updated, that is also done in the `ConditionsStore`.

Some conditions are not stored internally as key-value pairs. These are called "derived conditions". They are named such because the actual values of these conditions is derived from some other property stored elsewhere. Such as the "total ships" condition, whose value is derived from the player's collection of ships.

These derived conditions are handled within the `ConditionsStore` by `DerivedProvider` objects. The function `PlayerInfo::RegisterDerivedConditions` fills in all the necessary `DerivedProviders` in the player's `ConditionsStore` object so that they can produce the required values. This is done by first retrieving a reference to the `DerivedProvider` that will be used for each condition based on the condition name and then passing functions to it through the `SetGetFunction` and `SetSetFunction` functions. (And, formerly, the `SetEraseFunction`, and I think there might also have been a `SetHasFunction`.)

These functions will then allow the `ConditionsStore` to "get" and "set" the values for those conditions as appropriate (many derived conditions do not support "set", though, and so no such function is provided in those cases). For example, for the "total ships (all)" condition, the "get" function will provide the number of ships in the player's `ships` collection that are not destroyed, but it doesn't maike sense to try to set the number of ships the player has as a condition, so no "set" function is provided. It does make sense to set the "license: <license>" condition, though, since this is how licenses are granted or removed, and so a "set" function is provided. That function considers the value that the condition is being set to; if it is zero, the named license is removed, otherwise, the named license is added.

The `SetEraseFunction` method was removed because, as Peter said, the `eraseFunction` it sets was never actually used. The closest condition action to erasure is "clear", which sets the condition value to zero using the "set" function and so has no need for the "erase" function.

Why was this code calling `ConditionsStore::DerivedProvider::SetEraseFunction`? I can only speculate, but it's probably simply that it was there and it looked similar to the other functions, or because it was being used for other derived conditions.

**Comment by Zitchas** [comment]
Thanks for the explanation. It is much appreciated.

**Pull request merged**
