### PR TITLE
feat(data): Scaling Sol (and potentially other interesting things)

### PR DESCRIPTION
**Pull request by Zitchas**
**Content**
## Summary
This is expanding Sol to show what is possible when the system is larger and has more places for traffic to go internally. The end goal is to be big enough that it provides meaningful terrain for combat as a model for future endeavors.

## Details:

Just to start, Earth is set to 1496, and is of course = 1 AU 
(in other words 1 ES unit equals 100'000km, so Earth is at 149'600'000
(Just to be clear, 1 AU is actually = 149,597,870,700 m
Then all the main planets orbits have been scaled appropriately using their *average* orbital distance.

## Screenshots
None for now.

## Testing Done
Flying around Sol.

### CODE REVIEW

**Comment by bene-dictator** [comment]
Sol is already quite large by the scale of ES systems, so I don't expect you're going to do this for every system? (Much as I'd like to see that happen.)

The new landables, however, look cool.

**Comment by Zitchas** [comment]
> Sol is already quite large by the scale of ES systems, so I don't expect you're going to do this for every system? (Much as I'd like to see that happen.)
> 
> The new landables, however, look cool.

I'd love to do this to every system. I'd go so far as to say that, given how common uninhabitable planets and moons are in the galaxy, every inhabited system ought to have at least one uninhabitable something in it. And stations. Stations should be far more common.

I'm probably *not* going to do all of them. Definitely not in this PR, but I'd like to get a few done eventually.

**Comment by Zitchas** [comment]
Likewise, if anyone else wants to do a system or two, please do! Priority would be those systems that have major human campaign battles in them or ongoing conflicts; but any are welcome.

**Comment by Zitchas** [comment]
This doesn't make everything in Sol visitable. There's still a bunch of moons that really should be landable places. Hideouts for pirates, and the like :)

But the goal is to create something with some real *scale* to it. Something where yes, it will actually take you minutes to get from mercury to one of the outer solar system planets. Yes, you can actually get from Earth to Geyser (in Deneb) faster than you can get from Earth to Titan or Europa. This is intentional. It illustrates how these places have become bypassed by hyperdrive and easy access to other worlds. 

Seriously, I could envision an entire mini-campaign *just* flying around the Sol system. Throw in a few space stations (maybe a mining station in the asteroid belt, for instance), maybe a couple of pirate hideouts... There's so much room to play in here. And distances suddenly take on so much more meaning.

In any case, the point of this PR was to create a piece of sample terrain so that we can start seeing traffic flows and deal with threats at-range and the like. A proving ground of what is possible, in other words. That done, this is ready to go.

**Comment by TheGiraffe3** [comment]
Is it intentional that to get out of Sol you have to fly into the asteroid belt?

**Comment by Zitchas** [comment]
Yes. I think it probably needs to be just a bit farther out, though.

**Comment by TheGiraffe3** [comment]
And another question, why are some of the inhabited planets missing tribute definitions?
Too small?

**Comment by Zitchas** [comment]
Within Sol itself? Probably just missed. Even if it's just a hundred people and a couple of Barbs as their total defense force, most places should have something. (I could definitely see some places having pacifist beliefs and not having defenses, and others being prohibited from doing so by legal statues, but I'm not aware of anywhere in Sol being bound by either of these possibilities)

**Comment by TheGiraffe3** [comment]
I'll make a PR for that.

**Comment by xobes** [comment]
> And another question, why are some of the inhabited planets missing tribute definitions? Too small?

I've been pretty underwhelmed with the tribute (esp compared to salaries), and the battles to become usurper.

**Comment by xobes** [comment]
> > Sol is already quite large by the scale of ES systems, **so I don't expect you're going to do this for every system?** (Much as I'd like to see that happen.)

I didn't look (yet) -- but if what you're scaling is the orbits (only?) then if we thought that simply expanding on the orbital parameters were the goal, that should be doable with a [Python] script.

**Pull request merged**
