### PR TITLE
Engine slot review for the Ka'het, Remnant, Bunrodea, Gegno, and all Korath factions

### PR DESCRIPTION
**Pull request by TheGiraffe3**
Based on their descriptions.
Note that not all of the factions got engine slot changes; but their descriptions were reviewed to see if they needed more slots.

#87

### CODE REVIEW

**Comment by Zitchas** [comment]
I must admit, this is the harder batch. My general preference is for extra slots to be for things really designed for extra engines. A ship being designed for bigger than usual engines is not the same as being designed for multiple engines. 

If it's common for ships to be created with a "Thruster A + Thruster E" pairing, then there really should just be a thruster that is that size. Propulsion systems are sized to the typical space they have to occupy. It's much more efficient that way, unless one is purpose building a modular system (such as the Coalition, which are already done).

And this is also where the spreadsheet balance comparisons become problematic; although they might be able to work out a solution, too. Namely, the starship designers of the any particular alien faction have no clue about the sizes of human thrusters. And vice versa. Their engines should be sized appropriately for their ships; not sized specifically to fit into the human paradigm  of thrusters and then have extras added in to bring them up to the intended size.

**Comment by TheGiraffe3** [comment]
> I must admit, this is the harder batch. My general preference is for extra slots to be for things really designed for extra engines. A ship being designed for bigger than usual engines is not the same as being designed for multiple engines.
> 
> If it's common for ships to be created with a "Thruster A + Thruster E" pairing, then there really should just be a thruster that is that size. Propulsion systems are sized to the typical space they have to occupy. It's much more efficient that way, unless one is purpose building a modular system (such as the Coalition, which are already done).

My guess on this is that the shipyards put thruster A (which we'll say is the smallest in this example) on there more for show/convenience. A lot of captains will take it off to fit better outfits of other categories.
Or rather, they do A+E fully expecting E to be taken off by most captains. But it's still easier for most captains who will keep the extra thrust to switch it out for engine F then it is for the majority to switch from F to E (removing the thrust factor of A).

> And this is also where the spreadsheet balance comparisons become problematic; although they might be able to work out a solution, too. Namely, the starship designers of the any particular alien faction have no clue about the sizes of human thrusters. And vice versa. Their engines should be sized appropriately for their ships; not sized specifically to fit into the human paradigm of thrusters and then have extras added in to bring them up to the intended size.

Well, we could change the attributes so that each species can only install its type of engine on its ships, but that seems passively harmful rather then helpful in any way.

**Comment by Zitchas** [comment]
> Well, we could change the attributes so that each species can only install its type of engine on its ships, but that seems passively harmful rather then helpful in any way.

I have thought about that, and talked about it, but it's a unanimous conclusion that this would be harmful. 

The point I was actually getting at is that each family of thrusters/engines should be internally consistent to their faction and ships first and foremost, with considerations in alignment with other factions being secondary.

As I have mentioned elsewhere, I dislike "tacking in a tiny engine alonside a bigger one to fill up the available space." I do think there should be plenty of useful things that the player can do with that space, but I don't think that slapping in as many engines as can fit is a good one. Afterburners are one thing, for big boosts of temporary speed, and we already have those in-game. But having something like, say, a fuel optimization system that filters, pressurizes, and preps the fuel for optimum consumption and as a result boosts the thrust output of the ship by 10% would be something I'd like to see. By itself it does nothing, but it modifies the existing thruster to perform better. (numbers subject to balancing, of course. the 10% figure is just pulled out of thin air.)

Just taking a look at the automotive and aviation industry here on Earth, there are a *lot* of things that can be done to engines to improve them in various ways, ranging from more thrust, to more fuel efficiency, to cosmetic things like making smoke and colored flames. 

While leaving some of these ships without their extra filler engine might not make full use of space, but I also consider that a good thing. From a game interaction stand point, which is better?
a) The players buy a ship, and it comes all optimized and they just take it out and fly it as there is very little they can do to improve it.
b) The player buys a ship, and it comes reasonably outfitted, but there are a lot of ways the player can choose to make it better. They can just head out, but they can also swap in a bigger engine, or hire someone to do some modifications, or do some other tweaks. 

I personally find A to be both more fun, and more realistic. I don't expect cars to come fully optimized (otherwise a lot of specialty mechanics would be out of a job), and I don't expect ships to come that way either. More importantly, though, if I value a specific aspect of my ship (say, burst speed), I can choose to install an afterburner, and now I have chosen to do something that directly increases my enjoyment of the ship. This is generally makes the player feel like they are important and making a difference, which increases their enjoyment of the game.

From a realism side, most ships are made by corporations or entities that want to make some degree of profit. This means they aren't going to put a lot of effort into optimizing the performance of the ship, but rather into optimizing the profit margins. That means selecting outfits that are good enough to make the ship impressive and attract sales, but avoiding the best stuff that typically has a much higher price premium. Depending on the market, of course. In some markets purchasers might be attracted to a ship that comes with barely adequate outfitting to get out of port, never mind do anything exciting, but ship purchasers like buying it because it has an awesome potential if stripped of everything that came with it stock and re-outfitted with better gear. And some shipyards (especially niche resellers) will tend to sell things that are outfitted much better than others. The Marauder shipyards, for instance, are ones that I'd expect to be towards the higher end of their potential optimization, at least in the area that a particular ship specializes in.

We absolutely should have ships in game that are optimized to the limit. Because some ship captains who can afford to most definitely will. But that's the place for variants that appear in fleets, not stock ships in the shipyard. Stock ships that can or will someday be available for purchase should have room for **up**grades, not just **side**grades.

**Comment by TheGiraffe3** [comment]
So what would you like me to do? Keep the engines commented out, but put the slots in?

**Comment by Zitchas** [comment]
For right now, until we've got more input from the people involved in creating for the various alien factions, let's just stick to only adding additional slots to ships whose lore we have in-game specifically talks about having multiple engines. I know it's a bit restrictive, but it's a work in progress.

**Comment by TheGiraffe3** [comment]
And by lore, do you mean descriptions, or what?

**Comment by TheGiraffe3** [comment]
About to do something that may break this PR.

**Comment by Zitchas** [comment]
Ship descriptions is the most direct and obvious source, outfit descriptions can be as well (for instance, the Coalition's setup of being all about modular engines was based on MZ's original engine descriptions). Story content could also play into it.

**Comment by TheGiraffe3** [comment]
Most of the changes I've got here had to do with descriptions.

**Comment by Zitchas** [comment]
As per the comment in #96 , closing this to see if it impacts the ability to sync.

**Pull request closed without merging**
