### PR TITLE
Feat(update): 2024-12-16 conflict update (includes Strategic Scanning capabilities)

### PR DESCRIPTION
**Pull request by Zitchas**
Three commits upstream, most notably:
feat(scanning): extra and more finegrained tactical and strategic scanning options ](https://github.com/endless-sky/endless-sky/pull/8172)

Which was originally pioneered & used here in Delta back in #2 over a year and a half ago.

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
Will this fix the errors introduced by the 8172 merge?
```
Sprite "ui/range": 1 extra frames for the @2x sprite will be ignored.
Sprite "ui/tactical": 1 extra frames for the @2x sprite will be ignored.
Warning: image "ui/range" is referred to, but has no pixels.
Warning: image "ui/tactical" is referred to, but has no pixels.
```
Seems actual paths simply differ from what's defined in interface, but I see no change to those here, so probably not.

**Comment by Zitchas** [comment]
I'm not sure, to be honest.

**Comment by Zitchas** [comment]
I've been more focused on the compiling errors created by the removal of the erase functionality, I hadn't noticed these errors.

**Comment by Zitchas** [comment]
Actually, now that I've taken a moment to look at the failed checks... I'm not seeing anything about those two images. Where are you encountering it?

**Comment by SomeTroglodyte** [comment]
Just run normally (with high-dpi) - I keep a local master synced with git pulls and compile, and run from a terminal, so I see what's in errors.txt right away.

**Oh wait** - we're in Delta, I hadn't noticed following a link. I run upstream master up to 0d9b7fc.

**Comment by ziproot** [comment]
https://github.com/endless-sky/endless-sky/pull/8172#issuecomment-2558462276

**Pull request merged**
