### PR TITLE
feat(update): 2024-12-02 C - Remove extra tabs from two human missions (#10834)

### PR DESCRIPTION
**Pull request by Zitchas**
Just a regular update, not sure why the auto-sync isn't available for this.

### CODE REVIEW

**Comment by TheGiraffe3** [comment]
Looks like #148 is blocking it for some reason. Not sure why though; that branch doesn't have extraneous commits the way mine did.

**Comment by Zitchas** [comment]
How do you spot that? I'm familiar with the concept of GitHub trying to be helpful (maybe? lol) and removing the sync option when a PR would do it itself, but I'm curious how you can pick out 148 as being the one that is doing it.

**Comment by TheGiraffe3** [comment]
Currently on mobile, so not sure if that changes anything, but:
IMG_3324

**Comment by Zitchas** [comment]
Ah, thanks! I see it now. On web it's off in the same box, but located on the far right. I learned a  new thing today. :)

**Pull request merged**
