### PR TITLE
feat(Data): Hai Reveal Intro Bridge

### PR DESCRIPTION
**Pull request by Zitchas**
This PR is entirely the work of GreyMasterofGrey, PR'd here for merging with their permission.
----------------------
### Done:
- Reactivates disabled HR content.
- Restores changes to Wanderer's. _(Making them function in parallel is it's own entirely separate work.)_
- Generally cleans up changes to the files for consistency across the whole set.
- Undoes one change to post-war reactions that was never adequately justified.
- Corrects to the appropriate capitalisation of elders throughout the story.
- Adds a new name list for Hai-registered, human merchant ships now that they're used explicitly in a mission.
- Adds Total Missions: 14
- Supporting Events: 4 (2 timers, 2 actual)

### TBD Might be needed later?:
- Override first contact with the Quarg on Alta Hai if applicable. (See #7527 **| To-Do)**

~~Note: Opened early so if I've missed any little details in the restoration they can get picked up sooner rather than later.~~
Note: Ended up being more missions than expected when I actually planned it out, so WIP for a little while.

## Save File
Any save will do.

### CODE REVIEW

**Comment by Zitchas** [comment]
@MasterOfGrey If you could confirm that the summary I copied over is accurate and that there's nothing else that needs to be done here prior to merging, I'm good with merging this and then letting people playtest for themselves.

**Comment by Zitchas** [comment]
And just so that the connection exists: This is a direct PR of https://github.com/endless-sky/endless-sky/pull/8972

**Comment by MasterOfGrey** [comment]
Looks like it's all carried across just fine - obviously the Optional TBD and the Notes are outdated, but otherwise I believe the summary to be correct. (The WIP note was only still there courtesy of the ongoing dev debates on the end of HR)

This doesn't need anything doing to it (to the best of my knowledge) to make the current story fully functional.

**Comment by Zitchas** [comment]
Thanks. And thanks for having a PR for this. HR has been hidden away for far too long.

**Pull request merged**
