### PR TITLE
feat(content): Scaling Kornephoros

### PR DESCRIPTION
**Pull request by TheGiraffe3**
As requested in https://github.com/endless-sky/Endless-Sky-Delta/pull/52#issuecomment-2118868474, though I haven't added more landables.

### CODE REVIEW

**Comment by Zitchas** [comment]
In order to make it easier for people to check, as well as learn more about the system IRL, could you provide links to your source(s) please?

**Comment by TheGiraffe3** [comment]
I actually didn't have a reason to scale it _exactly_ this way, but roughly doubled it; the Wikipedia article isn't super descriptive. 
https://en.wikipedia.org/wiki/Beta_Herculis (and worth noting this is also Ruticulus).

**Comment by bene-dictator** [comment]
> https://en.wikipedia.org/wiki/Beta_Herculis (and worth noting this is also Ruticulus)

https://en.wikipedia.org/wiki/Rutilicus

**Comment by Zitchas** [comment]
Like with Sabik, my orbital mechanical theory is not cooperating, nor has been cooperating for a few weeks. I don't want to hold this up any longer in hopes that my brain starts cooperating in figuring out what the orbits look like and if this is the best fit for it.

That being said, I have tested this, and I find the new arrangement of things a bit farther out is nicer to fly in, so I'm going to merge this now.

If anyone wants to confirm (or make a PR with such adjustments as needed, if any) to bring it closer to real life, it'd be much appreciated.

**Pull request merged**
