### PR TITLE
Feat(update):2024 10 21conflict

### PR DESCRIPTION
**Pull request by Zitchas**
As per usual, just an update with a conflict.

### CODE REVIEW

**Comment by Zitchas** [comment]
The conflict is in the reversion of the "Hold Fire" command, specifically in the commands section. The comments on this are not particularly confidence inspiring, so I think I'm going to hold off on this update for a day or two.

**Comment by TheGiraffe3** [comment]
I guess my question is why don't we remove all our added code to resolve the conflict, merge master in, then add it again?
Actually, I could do that...

**Comment by TheGiraffe3** [comment]
> The conflict is in the reversion of the "Hold Fire" command, specifically in the commands section. The comments on this are not particularly confidence inspiring, so I think I'm going to hold off on this update for a day or two.

Alright, well, I've got a good way to do this (assuming that we don't want to revert the hold fire command as well). #108 should fix the problem.

**Comment by Zitchas** [comment]
I am ambivalent about the hold fire command. If it's bugged and breaking things, then I'd prefer to see it fixed. I would like to keep the functionality, preferably. 

But when they reverted it, it didn't really sound like they were very confident about not breaking things, and I'm more concerned about breaking other than the bug they are reverting it to get rid of. So this is more or less along the lines of "hold off for a day or three to make sure that this reversion didn't cause worse problems." Personally, the bug reported with it didn't sound very serious. So I'm curious as to whether this is a "pull down, and replace" type thing, or a "pull down, and break something", or a "pull down and then drop it for months or years." If it's the former, then I'll merge this. If it's the second, then I'd rather wait until they have that fixed, and *then* merge this. If it's the later, then I would prefer we keep the functionality in.

**Comment by Zitchas** [comment]
Closing this, will update via fresh PR.

**Pull request closed without merging**
