### PR TITLE
 feat(data): Expanding Alpha Centauri, and rearranging to be circumstellar rather than circumbinary

### PR DESCRIPTION
**Pull request by Quantumshark**
**Content**

Same changes as #66, but not broken.

## Summary
Larger, semi-real scaled Alpha Centauri (obviously, it's not possible to get it 100% accurate as there isn't support for elliptical orbits), with the planets orbiting the stars individually rather than both stars in the middle.

Ramscoop and solar collection will work weirdly until someone fixes the code to make them work from each star separately rather than the current approach of summing them across all stars and emanating all that from the centre of the system.

## Screenshots
image
image
image

## Testing Done
Went to the system and looked at it to check that the planets were in the right places

## Save File
This save file can be used to test these changes:
Any; just visit Alpha Centauri

## Performance Impact
Asteroid belt feels like it might be an issue, but it's less dense than the one you've got in Sol and I'm not aware of that one being a problem.

### CODE REVIEW

**Review by TheGiraffe3 — APPROVED** [review]

**Comment by Zitchas** [comment]
Thanks for reposting. 

Just as an aside for myself and anyone curious in the future, the wikipedia article on Alpha Centauri:
https://en.wikipedia.org/wiki/Alpha_Centauri

**Comment by Zitchas** [comment]
I should be able to test this at some point this week, sorry for taking a bit to get to it.

Could you update it please? 

If it's OK with you I can just hit the "update branch" button, but I don't want to risk breaking anything if you're using this branch elsewhere too.

**Comment by Quantumshark** [comment]
I hadn't noticed the update branch button before, so thank you for pointing it out.

**Comment by Zitchas** [comment]
You are welcome! And thank you for updating.

**Comment by Zitchas** [comment]
Sorry it's taken me longer than expected to get to this. Thanks for updating!

**Comment by TheGiraffe3** [comment]
@Zitchas what's the status on this?

**Comment by Zitchas** [comment]
The status is "waiting for me to have the capability and time to sit down and play it."

First I didn't have time, then I didn't have the capability to build it due to software failures. And then didn't have the capability due to hardware failures. So the delay is all on me at this point.

**Comment by Quantumshark** [comment]
No worries, these things take as long as they take.

And, feel free to hit the update branch button yourself when you've got time rather than waiting on me.

**Comment by Zitchas** [comment]
OK, this will be tested within the next 24h. For sure this time. *sigh*

**Review by TheGiraffe3 — APPROVED** [review]
I've retested. It certainly makes Alpha Centauri feel a lot bigger, and the player's (and others') ships a lot smaller.

~~and no, I definitely didn't test by demanding tribute~~

**Comment by Zitchas** [comment]
OK, I've finally tested it. Thanks for your patience, Quantumshark.

My thoughts:
a) To start off, it feels a bit disconcerting. Going to the center of the system, and finding... nothing there. Which is really unusual for ES, but is fitting Alpha Centauri's tri-star system. (and just to be clear, disconcerting is not a bad thing)
b) Flying around to find the stars and planets makes the system feel big. Just flying from one star to the other in a shuttle was about 38 seconds. Which feels like forever, but is really not that long. 
c) Space. As in, there's space for stuff to happen here. I can imagine a lot of possibilities to have something going on in each half of the system, have convoys going back and forth, etc.

All in all, I like it.

**Comment by Zitchas** [comment]
One thing in regards to the asteroid belt... It's very sparse and hard to really notice. I had trouble locating it.

edit: I eventually added a x10 to the strength of asteroid scanners, sold my HD, and loaded up my shuttle with 8 of them in order to see where the ring was. It's probably in a good location, but probably needs to be a bit more dense and/or more valuable, or the generic asteroids need to be removed. Right now, the generic ones are just dense enough to render the meaningful asteroids hard to distinguish a pattern.

**Review by Zitchas — APPROVED** [review]
We can tweak it more in the future, but I'm satisfied it's good enough to merge and include alongside other experiments.

Thanks!

**Pull request merged**
