### PR TITLE
Feat(code): Lateral Thrust and Drag Reduction

### PR DESCRIPTION
**Pull request by Zitchas**
**Feature:**

## Feature Details
- Minimizes the impact of drag on ships. It will now only kick in when above maximum speed or at less than 10% max velocity. Outside of these two extremes ships will operate without drag, which is to say a much more realistic method that actually feels like spacecraft.
- Implements left and right lateral thrust. Some might call it strafing, but I opted to call it lateral thrust because when an aircraft strafes a target it is generally doing a pass across it. Aircraft would call what this is sideslipping.
- Implements the control key as a modifier on turning, making the ship turn half as fast. 
- Implements lateral thrust flares. So if a ship has lateral engine points, it will get flares there using the standard engine flares.
- Implemented the `"lateral thrust ratio" X` attribute for ships.
- Implemented a default lateral thrust ratio.
- Added keybinds for left and right lateral thrust.
- The default lateral thrust ratio is now set in the gamerules.txt file, so content creators can change it without needing to rebuild the application.

As an explanation for the way lateral thrust is determined right now:
Lateral thrust is currently determined by applying a ratio to the ship's regular thrust, expressed as a decimal. So a ship with 0.3 lateral thrust ratio and 100k thrust would have 30k lateral thrust. 

## Thanks
Thanks go to Vitalchip for providing example code for parts of it and walking me through the process of writing this. It is very much appreciated.

## UI Screenshots
N/A

## Usage Examples
To assign a lateral thrust ratio to a ship, give the ship
`"lateral thrust ratio" X` 
where X is a number, with a number between 0 and 1 recommended, but not enforced. Negatives will flip it around so laterally thrusting right goes left and vice versa, while a number greater than 1 will result in a ship that can move laterally *faster* than it can accelerate forward. I can imagine ships where this could be the case, but they'd be unusual one-off designs.

Ships that don't have a value assigned will get the default value of 0.25.

My general thought is that heavies should be somewhere closer to 0.2, whereas fighters and the like should be closer to 0.8, but I really haven't done any testing on this yet. Vitalchip reports that in their experience, ships *must* have at least a little lateral thrust in order to stationkeep and stabilize. Logically, being able to stationkeep is a basic functionality of most spacecraft even in today's real world.

## Testing Done
Flying various pilots around the galaxy.

### Automated Tests Added
N/A

## Performance Impact
Unknown. I don't think there should be any, but there might be.

### CODE REVIEW

**Comment by RisingLeaf** [comment]
can you include a description of how the feature can be used and maybe a video of how it looks like?

**Comment by Zitchas** [comment]
Yes, I will. Not immediately, but I do plan on doing so. My first reaction, so far, is that it feels more organic. A lot more curves and swinging manouvers, a lot less straight lines from A to B. And it just *feels* good. I can swing around a ship to strafe it as I fly by. I'm not very good at it, but it honestly feels like I could potentially do some really neat things and actually be *rewarded* for spending time learning how to fly well with this. I mean, I kind of expected this from poking at it before, but the more I fly with it, the more impressed I am with how much it can improve the feel of flying in space.

I'll just add a note here that I've expanded a bit on what I initially wrote up there.
Improvements:
- Now each ship can be given an individual lateral thrust ratio.
- Ships that don't have a specified ratio will get the default value of 0.25
- The control key modifier will work on thrust, turn, and lateral thrust, for all those times when full-speed is just too fast.

**Comment by Zitchas** [comment]
Alright, I got an initial video flying around in a dreadnought with the pug taskforce. Everything's running with the default 0.25 lateral thrust value, so it's not particularly impressive.

https://youtu.be/ohC0hYxnPVc

**Comment by RisingLeaf** [comment]
Lots of unrelated changes

**Comment by Zitchas** [comment]
This looks like it'll be an ongoing issue, I'm not sure how to improve the process. The vast majority of those changes are merely things that have been committed to mainstream's master, 

For instance, starting at the top of the list. The diff is saying it's deleting "contributing.md" from the root endless sky directory. And when I go look at the experimental branch's root, contributing.md has already been deleted.

**Comment by Zitchas** [comment]
The default lateral thrust ratio value of 0.25 is now set in the gamerules.txt file, so it can be changed easily for testing purposes without having to rebuild/recompile the game.

**Pull request merged**
