### PR TITLE
feat(data): Expanding Alpha Centauri, and rearranging to be circumstellar rather than circumbinary

### PR DESCRIPTION
**Pull request by Quantumshark**
**Content**

Is this the kind of thing you're asking for [here](https://github.com/endless-sky/Endless-Sky-Delta/pull/52#issuecomment-2118868474)?

## Summary
Larger, semi-real scaled Alpha Centauri (obviously, it's not possible to get it 100% accurate as there isn't support for elliptical orbits), with the planets orbiting the stars individually rather than both stars in the middle.

Ramscoop and solar collection will work weirdly until someone fixes the code to make them work from each star separately rather than the current approach of summing them across all stars and emanating all that from the centre of the system.

## Screenshots
image
image
image

## Testing Done
Went to the system and looked at it to check that the planets were in the right places

## Save File
This save file can be used to test these changes:
Any; just visit Alpha Centauri

## Performance Impact
Asteroid belt feels like it might be an issue, but it's less dense than the one you've got in Sol and I'm not aware of that one being a problem.

### CODE REVIEW

**Review by TheGiraffe3 — APPROVED** [review]

**Comment by Zitchas** [comment]
This looks interesting.

**Comment by Zitchas** [comment]
Would you be able to update this please? I should be able to test it at some point this week, and potentially merge it.

**Comment by Quantumshark** [comment]
Evidently no, I would not be able to update it, because that's broken everything. Oops.

**Comment by Quantumshark** [comment]
I will reopen this from another branch.

**Pull request closed without merging**
