### PR TITLE
Feat(data): Creating a Person ship that is a Modified Protector

### PR DESCRIPTION
**Pull request by Zitchas**
I made this eons ago to be a person ship for someone who has put a lot of work into Endless Sky. They didn't want it, though, so it never went anywhere.

It recently came up in discussions that  ES really needs a bit more light-hearted things that are fun, and so I decided to bring back this person ship. I've obviously changed the names, and removed all the quotes. They were mostly kind of depressing, and in hindsight, it's disappointing that such quotes were so characteristic of someone so prominent in developing the game. So those phrases are gone. Now replaced with some much more cheerful, uplifting, and silly stuff. So I suppose all that remains of that original idea is the "crazy protector" part. I hope it brings joy to someone's day.

Oh, and added some more phrases to my person too.

So here it is, refurbished, and ready to *dance.*

2024-11-12 Sarcastic Protector Disco

### CODE REVIEW

**Review by TheGiraffe3 — APPROVED** [review]
I think it does make sense for Amazinite to get a person.
Should a Protector this powerful be uncapturable/never disabled though?
Probably fine for it not to be, as it'd be hard to disable, just a thought.

**Comment by Zitchas** [comment]
It's not Amaszinite, it's "Random Author" (and for reference, Amazinite declined having a person ship, and did mention on discord wanting it to be a Protector. Who knows, he might have been joking. Definitely declined it when it came to being PR'd, though.)

And it does have "Never disabled"

**Comment by TheGiraffe3** [comment]
> It's not Amazinite, it's "Random Author"

Well, it's called "Random Author" in game, but the commits earlier and the PR to upstream kind of give it away 😉 

> And it does have "Never disabled"

Oh right, I had been looking at the ship definition.

**Comment by Zitchas** [comment]
That's true, they do. That being said, with all the quotes removed and replaced, at this point in time absolutely zero of those quotes are attributable to him.

**Comment by Zitchas** [comment]
Actually, just to ensure there's no confusion about that, I'm closing this and Re-PRing. Wouldn't want him to get associated with quotes that aren't his.

**Pull request closed without merging**
