### PR TITLE
Feat(plugins): Install and update plugins within ES

### PR DESCRIPTION
**Pull request by RisingLeaf**
## Feature Details
https://github.com/endless-sky/endless-sky/discussions/9058 -> Discussion
https://github.com/endless-sky/endless-sky/issues/707 -> Issue that requests this.
[RFC](https://github.com/endless-sky/rfcs/blob/main/rfcs/0001-plugin-index.md) -> RFC from the issue

This pull request implements a feature that is supposed to make plugins easier to install and update, cause with this PR, you can do it in game (requires a restart though, don't annoy me with details).

What I am doing is downloading [this](https://github.com/endless-sky/endless-sky-plugins/blob/master/generated/plugins.json) json file via curl, parsing it with the [nlohmann json library](https://github.com/nlohmann/json) and extract all necessary data about the plugins, they are then displayed in a new sub tab of the plugins menu, where you can install them, which happens over [curl](https://curl.se/libcurl/) and [libarchive](http://libarchive.org/).

After a quick restart the plugin will then be available.

To update a plugin one again has to go to the sub tab, navigate to the plugin and press "update", the name of the plugin will be yellow if it is outdated, which deletes the plugin directory and downloads it again.

Pages for the list are already implemented,with buttons to switch between them.

The json file gets updated everytime you open the preferences panel, as long as you have an active internet connection.

 
## Testing Done
linux, yes
mac, yes
windows, yes, thx quyykk

### Automated Tests Added
No?

## Performance Impact
N/A

## TODO List:
- [x] Download the json file every time ES gets opened
- [x] Think about life, then remove gitlib2 and just download zips (people will probably have to force me to that)
- [x] Make the UI look nice
- [x] Add buttons for the pages so that people dont have to know that "e" and "r" switch pages
- [x] polish
- [x] limit file size

now for delta cause why not?

### CODE REVIEW

**Comment by Zitchas** [comment]
This looks rather useful in making plug-ins both more accessible and much easier to use. Thanks for the PR!

At first glance, I'm not sure why plugins.h would conflict.
 PreferencePanel, though... If something touches that, I'm never surprised when there are conflicts. 
The keys panel... hmmm.... I'll take a look.

**Comment by Zitchas** [comment]
Ah, found it here: 
https://github.com/endless-sky/Endless-Sky-Delta/commit/196acb1defc906a5de22bf1b80fdc6bb6cbe8756#diff-e751bd0843b3b427cfbcd286d4e639280a2a410d9082cff38fa4bd969a183b6e

Basically, I replaced the Keys panel.png with a version of the picture where the shift panel was removed, and now the shift panel is a separate panel that can be moved around in interfaces.txt so that we didn't need to make a new set of images every time something changed the position of the keys and the shift values got un-aligned.

**Comment by RisingLeaf** [comment]
I see in that case I will have to duplicate my own branch to resolve this as it is the same branch as for the main repo

**Comment by RisingLeaf** [comment]
Next week I will have the time to do so.

**Comment by Zitchas** [comment]
I'm not sufficiently awake to look into it right now, but I might be able to revert that change. If I recall correctly since the time I implemented it they changed how things work so the shift panel is just a message instead of being something that has to keep certain labels precisely lined up with lines in the main box next to them.  If I am indeed remembering correctly, then that change can probably be reverted out, solving that particular conflict. 

I'm kind of at a loss regarding the plugins.h one, though, as I can't recall having done anything in there. Could you tell me what line the coinflict(s) is/are on?

**Comment by Zitchas** [comment]
Ah, the conflict in plugins.h is upstream. So that conflict can be resolved in this branch, since it's equally required for upstream merging too.

Likewise, upstream also shows a conflict in preferencesPanel.cpp; which might take care of some of it, but it wouldn't surprise me if there are still some here too.

https://github.com/endless-sky/endless-sky/pull/9068

**Comment by warp-core** [comment]
The conflict is probably from 49d55f1 which is not unique to this repository, but this branch hasn't been updated with it from upstream yet. I expect the PR over has the same conflict in that file.

**Comment by RisingLeaf** [comment]
These two conflicts should be resolved now.

**Comment by Zitchas** [comment]
I don't think I'm going to be able to pre-emtively fix the potential conflict. 

Just choose to keep your own graphics, and worse comes to worse I'll have to do a "touch up" PR after the fact to adjust a position or two.

**Comment by Zitchas** [comment]
I guess we'll see how https://github.com/endless-sky/Endless-Sky-Delta/pull/65 goes. If it will go cleanly, then great, if not...

**Comment by RisingLeaf** [comment]
#65 should not resolve the conflict as it does not affect the sprite

**Comment by Zitchas** [comment]
Hmm, yeah, it just corrects some positioning from the earlier commit. 

https://github.com/endless-sky/Endless-Sky-Delta/commit/196acb1defc906a5de22bf1b80fdc6bb6cbe8756

is where the sprite is added.

**Comment by Zitchas** [comment]
Sorry, VS updated and now it won't build anything anymore. 
`CMake Error: CMake was unable to find a build program corresponding to "Ninja Multi-Config".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.`

Not sure how long this will take to fix this.

**Comment by RisingLeaf** [comment]
no hurry

**Comment by Zitchas** [comment]
45min of fighting with it, I'm giving up for now. Next step is to delete and redownload the local repository in case there's some hidden git ignored local setting or something that got set (or unset) somewhere.

**Comment by Zitchas** [comment]
Is this fully up to date? Just looking at the changed files, GitHub is saying there are 205 of them, and a lot of it is stuff that I am fairly sure it's other PRs, not yours. Not really sure what GitHub is doing with them, but it makes it hard to examine.

**Comment by RisingLeaf** [comment]
There is definitely something broken going on. Is delta up to date with master?

**Comment by Zitchas** [comment]
It was when I last posted, but it's currently out of date with the most recent set, which have a few conflicts. If they're simple I can take care of it now. If they're not... Should be able to within the next 48h unless they're really bad.

edit: the conflict was so minor as to make me wonder why it was one at all. Basically just a conflict with the fact that our experiment completing Sol had the planet Uranus created in the same spot of the map file as an Incipias planet. So just an extremely minor conflict resolution to ensure both are kept. It'll be merged as soon as the checks are complete.

**Comment by Zitchas** [comment]
Regarding the conflict with the keys panel.png, just choose to overwrite with yours. When I merge I will do a follow up with any changes needed to keep things looking good (if necessary).

(and Delta is now up to date with upstream once again)

**Comment by Zitchas** [comment]
Just looking through the changelist, and it looks like almost every change that has happened to upstream in the several months, maybe longer. My only idea is that the conflict is causing github to rollback to the last place in Delta's history that this PR wouldn't conflict with, and display the diff based on that. 

As mentioned in my previous post, I'm good this PR overwriting the keys panel.png. I have access to the old files (and svg if necessary to recreate things), so best case, it works with your ovewritten version (which I think it might, but not 100%), and worst case, I have to do a follow up PR to resolve the panels. I'm good with that too. But I'll know better once I can see a proper diff.

**Comment by warp-core** [comment]
Something about the way GitHub handles PRs seems to just lead it to not really update the diff when the same commits are applied to both the head and base branches after the PR is opened.
If you start the process of opening a new PR with these same branches, you can see it only shows 176 commits and 17 changed files with 801 additions and 34 deletions (at the moment).

**Comment by Zitchas** [comment]
Interesting observation. I'm fairly sure I've seen it resolved somewhere in the past, but not sure how.

**Comment by RisingLeaf** [comment]
I might just try to open a new one

**Pull request closed without merging**
