### PR TITLE
Use a new directory for saves, and bump the "previous saves" number to five

### PR DESCRIPTION
**Pull request by TheGiraffe3**
**Warning: This is written as if you use macOS. I don't know how other operating systems work, and don't know how to describe the changes.**

Creates a new Application Support directory for Delta.
Now saves and plugins are installed separately. Delta uses plugin/save folders inside of the `endless-sky-delta` folder.
Upstream still uses the `endless-sky` folder.
This means that pilots that use Delta will need to be transferred, but nothing bad will happen to pilots that want to not use the engine slot system, for example.

Alphabetizes the .codespell.words.exclude file.

Makes the amount of previous saves be five, as opposed to three.

### CODE REVIEW

**Comment by TheGiraffe3** [comment]
I'm hoping that the copyright check failing doesn't block this.
I've noticed that all PRs that change the copyright upstream are having the same error message.
Here I have trouble because of merging master, which has the Successors.

**Comment by Zitchas** [comment]
Thanks for doing this! It will be a few days before I can actually look into it, but I had been thinking that doing this would probably be a good idea. There are enough preference differences, too, including things like the lateral thrust keys, that would benefit from not being reset between versions.

**Comment by Zitchas** [comment]
Note: I will update experimental to be up to date with upstream and resolve the conflict separately, too. That should make things easier.

**Comment by TheGiraffe3** [comment]
The real change is in source/Files.cpp. In theory, that's the only thing that needs to be changed.
Everything else besides .codespell.words.exclude is a product of the master merge. 
I'll fix the data file check shortly.

**Comment by TheGiraffe3** [comment]
> Note: I will update experimental to be up to date with upstream and resolve the conflict separately, too. That should make things easier.

Just saw this.

Your choice, the conflict wasn't that bad. I have everything done already though, so in the interests of saving trouble it might be easier to do that here.

**Comment by TheGiraffe3** [comment]
[This](https://github.com/endless-sky/Endless-Sky-Delta/pull/78/files?file-filters%5B%5D=.cpp&show-viewed-files=true#diff-a27fe2e99c1305448c850f721f9da020cd938a10323ff481f7559bd4ffd941f2) is the actual content of the PR.

**Comment by TheGiraffe3** [comment]
Side question: do we want Delta to have a greater number of previous saves? And if so, how many? Ten?

**Comment by Zitchas** [comment]
OK, I'm back at a proper keyboard and can actually type up more detailed stuff.

I've got an update PR going on the side here so that it can be dealt with separately so in this PR I can focus on your changes rather than dealing with upstream's too.

We should probably formulate a "guide to PRs" somewhere to describe some general "best practices" to keep things working smoothly, but one such thing is keeping PRs focused. For example in this case, having the updating from upstream as a separate thing from the changes to the preference/save directory. Changing the number of saves is thematically relevant as part of the general changes to the save location, so that's OK too.

In this particular case, the upstream update seems to have something broken in it, so having the stand-alone update process will be useful in determining which PR on their end actually broke things. I might be able to go back in time and just do everything up to just before that point or something in order to move it forward as much as possible without actually breaking anything while we wait for upstream to actually fix the problem. Not to mention figure out if it's something that is broken on their end, or if it's something that is getting broken on our side.

----

As to the number of saves, yes, I think that the number of saves should be increased a bit. I don't think it needs to be increased a lot, though. Maybe +2? I don't think we need to have a huge number of saves, but a few more would be very much welcome.

**Comment by Zitchas** [comment]
Resolved one minor conflict with codespell, which is merely a change in order of a few words, so very simple to resolve.

**Comment by TheGiraffe3** [comment]
Theoretically this should work. However, I'm not sure if Delta has other changes that may cause bugs.

**Comment by Zitchas** [comment]
I think it is probably as simple as that. :)

I'm uncertain as to why there are the additions to the planet list included in here. Aren't those from the Successors PR?

Much simpler to review now. :) Anyway, your changes look good, although I'm uncertain as to why there are the additions to the planet list included in here. Aren't those from the Successors PR?

**Comment by TheGiraffe3** [comment]
I'm not sure why those would be there either. Did they somehow not get merged in as part of #79?

**Comment by Zitchas** [comment]
Something in the git history when updating experimental then updating this must have gotten mixed up. Looking up in the file, it appears these two entries have been duplicated in this PR.

**Comment by TheGiraffe3** [comment]
~~How do you mean?~~
Ah, I see.

**Comment by TheGiraffe3** [comment]
> Something in the git history when updating experimental then updating this must have gotten mixed up. Looking up in the file, it appears these two entries have been duplicated in this PR.

Yes, that's what it was. I've got that fixed now though.

**Comment by Zitchas** [comment]
Looks good to me. For something like this I'd like to test it before merging, but assuming it works as described.... :)

**Comment by TheGiraffe3** [comment]
You could download it from the checks. Granted, it's more work than using ESLauncher2, but seeing as how that doesn't work for this repository, I think downloading it like that is the only way to test.

**Comment by Zitchas** [comment]
Yes, downloading from the check artifacts is exactly how I did it.

- [x] created a new directory where it was supposed to
- [x] the newly created save was created in the appropriate folder
- [x] other files created where they were supposed to be.
- [x] Nothing was touched in the "endless sky" folder

**Comment by TheGiraffe3** [comment]
Great! Glad I was able to help.

**Pull request merged**
