### PR TITLE
feat(content): Add a defense fleet to planets in Sol that are missing one

### PR DESCRIPTION
**Pull request by TheGiraffe3**
https://github.com/endless-sky/Endless-Sky-Delta/pull/52#issuecomment-2399462083

### CODE REVIEW

**Comment by TheGiraffe3** [comment]
I do not understand why the checks would be failing.

**Comment by Zitchas** [comment]
The failed check gives the following warning:
`Warning: fleet "Sol Defense Fleet" is referred to, but not fully defined.`

That probably means that somewhere is referring to this fleet, but the fleet definition isn't complete or otherwise has a problem.

**Comment by TheGiraffe3** [comment]
> The failed check gives the following warning: `Warning: fleet "Sol Defense Fleet" is referred to, but not fully defined.`
> 
> That probably means that somewhere is referring to this fleet, but the fleet definition isn't complete or otherwise has a problem.

Ah yes, thanks. Turns out that I've been using `add variant` in plugins too much recently, and forgot the other metadata.

**Comment by Zitchas** [comment]
Just for the record so others can see how I found that:

1. left-click on one of the red Xs next to one of the commits.
2. A small sub-window will appear saying "Some of the checks were not successful" along with a list of checks.
3. Find one of the checks that has a red X next to it. 
4. Click on "details"
5. It will take you to a new page with a large command-line-style info box occupying a lot of it.
6. Most of the lines will have grey checkmarks or black-and-grey circles with a line through it. Ignore these. Look for the line that has a red X.
7. In this case that is the "Parse Datafiles" line. It will usually be expanded to give some details, but if it isn't, you can click on the > next to it to do so.
8. Sometimes there will be useful information right here. In this case, it does, stating `Warning: fleet "Sol Defense Fleet" is referred to, but not fully defined."`.
9. If it doesn't provide any useful information, you can click on the solid arrow to get more information. Many of the code checks will require you do to this, as they are fairly verbose, and will often provide specific line references.

Hopefully this is helpful to you or someone in the future. It's my typical starting point when a check doesn't complete. So long as the problem is in the data or code itself, then these checks can be pretty helpful in locating problems. If the failure is in one of the tests or dlls, though... Those are a lot more finicky and generally hard to troubleshoot. I generally recommend redoing the test to see if it repeats.

**Review by Zitchas — APPROVED** [review]
Looks suitable. Thanks!

**Pull request merged**
